using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using QLCuaHangDDS.BUS;

namespace QLCuaHangDDS.GUI.ManHinhDichVu
{
    public partial class DichVu : DevExpress.XtraEditors.XtraForm
    {
        public DichVu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new QLCuaHangDDS.DAO.QLCuaHangDDSDBDataContext().DICHVUs;

            gridView1.Columns[0].Caption = "Tên dịch vụ";
            gridView1.Columns[1].Caption = "Giá (VNĐ)";
        }
        private void RefreshTableData(object sender, FormClosedEventArgs e)
        {
            gridControl1.DataSource = new QLCuaHangDDS.DAO.QLCuaHangDDSDBDataContext().DICHVUs;
        }
        private void simpleButton1_Click(object sender, EventArgs e)
        {
            ThemDV form = new ThemDV();
            form.Show();
            form.FormClosed += RefreshTableData;
        }
        
        private void simpleButton3_Click(object sender, EventArgs e)
        {
            String tenDv = this.gridView1.GetRowCellValue(this.gridView1.FocusedRowHandle, "TenDV").ToString();
            String giaDv = this.gridView1.GetRowCellValue(this.gridView1.FocusedRowHandle, "DonGia").ToString();
            SuaDV form = new SuaDV(tenDv, giaDv);
            form.Show();
            form.FormClosed += RefreshTableData;
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            if (XtraMessageBox.Show("Bạn có chắc chắn muốn xóa Dịch vụ " + this.gridView1.GetRowCellValue(this.gridView1.FocusedRowHandle, "TenDV").ToString() +" ?", "Waring", MessageBoxButtons.OKCancel, MessageBoxIcon.Warning) == DialogResult.OK)
            {
                String tenDv = this.gridView1.GetRowCellValue(this.gridView1.FocusedRowHandle, "TenDV").ToString();

                if (DichVuBUS.XoaDichVu(tenDv))
                {
                    XtraMessageBox.Show("Xóa thành công!", "Succeed!", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    this.RefreshTableData(null, null);
                }
                else
                {
                    XtraMessageBox.Show("Xóa thất bại!", "Failed!", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
    }
}