<?xml version="1.0" encoding="utf-8"?><Database Name="QLCuaHangDDS" Class="QLCuaHangDDSDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-S11NQI2;Initial Catalog=QLCuaHangDDS;Integrated Security=True" SettingsObjectName="QLCuaHangDDS.Properties.Settings" SettingsPropertyName="QLCuaHangDDSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.HANGSANXUAT" Member="HANGSANXUATs">
    <Type Name="HANGSANXUAT">
      <Column Name="TenHangSX" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="HANGSANXUAT_MATHANG" Member="MATHANGs" ThisKey="TenHangSX" OtherKey="TenHangSX" Type="MATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.BANGSUACHUA" Member="BANGSUACHUAs">
    <Type Name="BANGSUACHUA">
      <Column Name="MaBSC" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenMHSC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="BANGSUACHUA_CHITIETHOADONSUACHUA" Member="CHITIETHOADONSUACHUAs" ThisKey="MaBSC" OtherKey="MaBSC" Type="CHITIETHOADONSUACHUA" />
    </Type>
  </Table>
  <Table Name="dbo.BAOCAOTHANG" Member="BAOCAOTHANGs">
    <Type Name="BAOCAOTHANG">
      <Column Name="MaBC" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayLapBC" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NguoiLap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongDoanhThu" Type="System.Single" DbType="Real" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADONBANHANG" Member="CHITIETHOADONBANHANGs">
    <Type Name="CHITIETHOADONBANHANG">
      <Column Name="MaChiTietHD" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MaMH" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="HOADONBANHANG_CHITIETHOADONBANHANG" Member="HOADONBANHANG" ThisKey="MaHD" OtherKey="MaHD" Type="HOADONBANHANG" IsForeignKey="true" />
      <Association Name="MATHANG_CHITIETHOADONBANHANG" Member="MATHANG" ThisKey="MaMH" OtherKey="MaMH" Type="MATHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADONSUACHUA" Member="CHITIETHOADONSUACHUAs">
    <Type Name="CHITIETHOADONSUACHUA">
      <Column Name="MaCTSC" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHDSC" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MaBSC" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="BANGSUACHUA_CHITIETHOADONSUACHUA" Member="BANGSUACHUA" ThisKey="MaBSC" OtherKey="MaBSC" Type="BANGSUACHUA" IsForeignKey="true" />
      <Association Name="HOADONSUACHUA_CHITIETHOADONSUACHUA" Member="HOADONSUACHUA" ThisKey="MaHDSC" OtherKey="MaHDSC" Type="HOADONSUACHUA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITTIETHOADONDICHVU" Member="CHITTIETHOADONDICHVUs">
    <Type Name="CHITTIETHOADONDICHVU">
      <Column Name="MaCTDV" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaHDDV" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MaDV" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DICHVU_CHITTIETHOADONDICHVU" Member="DICHVU" ThisKey="MaDV" OtherKey="MaDV" Type="DICHVU" IsForeignKey="true" />
      <Association Name="HOADONDICHVU_CHITTIETHOADONDICHVU" Member="HOADONDICHVU" ThisKey="MaHDDV" OtherKey="MaHDDV" Type="HOADONDICHVU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DICHVU" Member="DICHVUs">
    <Type Name="DICHVU">
      <Column Name="MaDV" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="DICHVU_CHITTIETHOADONDICHVU" Member="CHITTIETHOADONDICHVUs" ThisKey="MaDV" OtherKey="MaDV" Type="CHITTIETHOADONDICHVU" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONBANHANG" Member="HOADONBANHANGs">
    <Type Name="HOADONBANHANG">
      <Column Name="MaHD" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="HOADONBANHANG_CHITIETHOADONBANHANG" Member="CHITIETHOADONBANHANGs" ThisKey="MaHD" OtherKey="MaHD" Type="CHITIETHOADONBANHANG" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONDICHVU" Member="HOADONDICHVUs">
    <Type Name="HOADONDICHVU">
      <Column Name="MaHDDV" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="HOADONDICHVU_CHITTIETHOADONDICHVU" Member="CHITTIETHOADONDICHVUs" ThisKey="MaHDDV" OtherKey="MaHDDV" Type="CHITTIETHOADONDICHVU" />
    </Type>
  </Table>
  <Table Name="dbo.HOADONSUACHUA" Member="HOADONSUACHUAs">
    <Type Name="HOADONSUACHUA">
      <Column Name="MaHDSC" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaPH" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Association Name="HOADONSUACHUA_CHITIETHOADONSUACHUA" Member="CHITIETHOADONSUACHUAs" ThisKey="MaHDSC" OtherKey="MaHDSC" Type="CHITIETHOADONSUACHUA" />
      <Association Name="PHIEUHEN_HOADONSUACHUA" Member="PHIEUHEN" ThisKey="MaPH" OtherKey="MaPH" Type="PHIEUHEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIMATHANG" Member="LOAIMATHANGs">
    <Type Name="LOAIMATHANG">
      <Column Name="MaLoaiMH" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiMH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAIMATHANG_MATHANG" Member="MATHANGs" ThisKey="MaLoaiMH" OtherKey="MaLoaiMH" Type="MATHANG" />
    </Type>
  </Table>
  <Table Name="dbo.MATHANG" Member="MATHANGs">
    <Type Name="MATHANG">
      <Column Name="MaMH" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaLoaiMH" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TenMH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="TenHangSX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NamSX" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KinhDoanh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MATHANG_CHITIETHOADONBANHANG" Member="CHITIETHOADONBANHANGs" ThisKey="MaMH" OtherKey="MaMH" Type="CHITIETHOADONBANHANG" />
      <Association Name="LOAIMATHANG_MATHANG" Member="LOAIMATHANG" ThisKey="MaLoaiMH" OtherKey="MaLoaiMH" Type="LOAIMATHANG" IsForeignKey="true" />
      <Association Name="HANGSANXUAT_MATHANG" Member="HANGSANXUAT" ThisKey="TenHangSX" OtherKey="TenHangSX" Type="HANGSANXUAT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEUHEN" Member="PHIEUHENs">
    <Type Name="PHIEUHEN">
      <Column Name="MaPH" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayLap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="TinhTrangMay" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="PHIEUHEN_HOADONSUACHUA" Member="HOADONSUACHUAs" ThisKey="MaPH" OtherKey="MaPH" Type="HOADONSUACHUA" />
    </Type>
  </Table>
  <Table Name="dbo.QUYDINH" Member="QUYDINHs">
    <Type Name="QUYDINH">
      <Column Name="MaQD" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQD" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>