#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCuaHangDDS.DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCuaHangDDS")]
	public partial class QLCuaHangDDSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBANGSUACHUA(BANGSUACHUA instance);
    partial void UpdateBANGSUACHUA(BANGSUACHUA instance);
    partial void DeleteBANGSUACHUA(BANGSUACHUA instance);
    partial void InsertBAOCAOTHANG(BAOCAOTHANG instance);
    partial void UpdateBAOCAOTHANG(BAOCAOTHANG instance);
    partial void DeleteBAOCAOTHANG(BAOCAOTHANG instance);
    partial void InsertCHITIETHOADONBANHANG(CHITIETHOADONBANHANG instance);
    partial void UpdateCHITIETHOADONBANHANG(CHITIETHOADONBANHANG instance);
    partial void DeleteCHITIETHOADONBANHANG(CHITIETHOADONBANHANG instance);
    partial void InsertCHITIETHOADONSUACHUA(CHITIETHOADONSUACHUA instance);
    partial void UpdateCHITIETHOADONSUACHUA(CHITIETHOADONSUACHUA instance);
    partial void DeleteCHITIETHOADONSUACHUA(CHITIETHOADONSUACHUA instance);
    partial void InsertCHITTIETHOADONDICHVU(CHITTIETHOADONDICHVU instance);
    partial void UpdateCHITTIETHOADONDICHVU(CHITTIETHOADONDICHVU instance);
    partial void DeleteCHITTIETHOADONDICHVU(CHITTIETHOADONDICHVU instance);
    partial void InsertDICHVU(DICHVU instance);
    partial void UpdateDICHVU(DICHVU instance);
    partial void DeleteDICHVU(DICHVU instance);
    partial void InsertHANGSANXUAT(HANGSANXUAT instance);
    partial void UpdateHANGSANXUAT(HANGSANXUAT instance);
    partial void DeleteHANGSANXUAT(HANGSANXUAT instance);
    partial void InsertHOADONBANHANG(HOADONBANHANG instance);
    partial void UpdateHOADONBANHANG(HOADONBANHANG instance);
    partial void DeleteHOADONBANHANG(HOADONBANHANG instance);
    partial void InsertHOADONDICHVU(HOADONDICHVU instance);
    partial void UpdateHOADONDICHVU(HOADONDICHVU instance);
    partial void DeleteHOADONDICHVU(HOADONDICHVU instance);
    partial void InsertHOADONSUACHUA(HOADONSUACHUA instance);
    partial void UpdateHOADONSUACHUA(HOADONSUACHUA instance);
    partial void DeleteHOADONSUACHUA(HOADONSUACHUA instance);
    partial void InsertLOAIMATHANG(LOAIMATHANG instance);
    partial void UpdateLOAIMATHANG(LOAIMATHANG instance);
    partial void DeleteLOAIMATHANG(LOAIMATHANG instance);
    partial void InsertMATHANG(MATHANG instance);
    partial void UpdateMATHANG(MATHANG instance);
    partial void DeleteMATHANG(MATHANG instance);
    partial void InsertPHIEUHEN(PHIEUHEN instance);
    partial void UpdatePHIEUHEN(PHIEUHEN instance);
    partial void DeletePHIEUHEN(PHIEUHEN instance);
    partial void InsertQUYDINH(QUYDINH instance);
    partial void UpdateQUYDINH(QUYDINH instance);
    partial void DeleteQUYDINH(QUYDINH instance);
    #endregion
		
		public QLCuaHangDDSDBDataContext() : 
				base(global::QLCuaHangDDS.Properties.Settings.Default.QLCuaHangDDSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangDDSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangDDSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangDDSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCuaHangDDSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BANGSUACHUA> BANGSUACHUAs
		{
			get
			{
				return this.GetTable<BANGSUACHUA>();
			}
		}
		
		public System.Data.Linq.Table<BAOCAOTHANG> BAOCAOTHANGs
		{
			get
			{
				return this.GetTable<BAOCAOTHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETHOADONBANHANG> CHITIETHOADONBANHANGs
		{
			get
			{
				return this.GetTable<CHITIETHOADONBANHANG>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETHOADONSUACHUA> CHITIETHOADONSUACHUAs
		{
			get
			{
				return this.GetTable<CHITIETHOADONSUACHUA>();
			}
		}
		
		public System.Data.Linq.Table<CHITTIETHOADONDICHVU> CHITTIETHOADONDICHVUs
		{
			get
			{
				return this.GetTable<CHITTIETHOADONDICHVU>();
			}
		}
		
		public System.Data.Linq.Table<DICHVU> DICHVUs
		{
			get
			{
				return this.GetTable<DICHVU>();
			}
		}
		
		public System.Data.Linq.Table<HANGSANXUAT> HANGSANXUATs
		{
			get
			{
				return this.GetTable<HANGSANXUAT>();
			}
		}
		
		public System.Data.Linq.Table<HOADONBANHANG> HOADONBANHANGs
		{
			get
			{
				return this.GetTable<HOADONBANHANG>();
			}
		}
		
		public System.Data.Linq.Table<HOADONDICHVU> HOADONDICHVUs
		{
			get
			{
				return this.GetTable<HOADONDICHVU>();
			}
		}
		
		public System.Data.Linq.Table<HOADONSUACHUA> HOADONSUACHUAs
		{
			get
			{
				return this.GetTable<HOADONSUACHUA>();
			}
		}
		
		public System.Data.Linq.Table<LOAIMATHANG> LOAIMATHANGs
		{
			get
			{
				return this.GetTable<LOAIMATHANG>();
			}
		}
		
		public System.Data.Linq.Table<MATHANG> MATHANGs
		{
			get
			{
				return this.GetTable<MATHANG>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUHEN> PHIEUHENs
		{
			get
			{
				return this.GetTable<PHIEUHEN>();
			}
		}
		
		public System.Data.Linq.Table<QUYDINH> QUYDINHs
		{
			get
			{
				return this.GetTable<QUYDINH>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGSUACHUA")]
	public partial class BANGSUACHUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaBSC;
		
		private string _TenMHSC;
		
		private System.Nullable<double> _DonGia;
		
		private EntitySet<CHITIETHOADONSUACHUA> _CHITIETHOADONSUACHUAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBSCChanging(long value);
    partial void OnMaBSCChanged();
    partial void OnTenMHSCChanging(string value);
    partial void OnTenMHSCChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public BANGSUACHUA()
		{
			this._CHITIETHOADONSUACHUAs = new EntitySet<CHITIETHOADONSUACHUA>(new Action<CHITIETHOADONSUACHUA>(this.attach_CHITIETHOADONSUACHUAs), new Action<CHITIETHOADONSUACHUA>(this.detach_CHITIETHOADONSUACHUAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBSC", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaBSC
		{
			get
			{
				return this._MaBSC;
			}
			set
			{
				if ((this._MaBSC != value))
				{
					this.OnMaBSCChanging(value);
					this.SendPropertyChanging();
					this._MaBSC = value;
					this.SendPropertyChanged("MaBSC");
					this.OnMaBSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMHSC", DbType="NVarChar(50)")]
		public string TenMHSC
		{
			get
			{
				return this._TenMHSC;
			}
			set
			{
				if ((this._TenMHSC != value))
				{
					this.OnTenMHSCChanging(value);
					this.SendPropertyChanging();
					this._TenMHSC = value;
					this.SendPropertyChanged("TenMHSC");
					this.OnTenMHSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGSUACHUA_CHITIETHOADONSUACHUA", Storage="_CHITIETHOADONSUACHUAs", ThisKey="MaBSC", OtherKey="MaBSC")]
		public EntitySet<CHITIETHOADONSUACHUA> CHITIETHOADONSUACHUAs
		{
			get
			{
				return this._CHITIETHOADONSUACHUAs;
			}
			set
			{
				this._CHITIETHOADONSUACHUAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOADONSUACHUAs(CHITIETHOADONSUACHUA entity)
		{
			this.SendPropertyChanging();
			entity.BANGSUACHUA = this;
		}
		
		private void detach_CHITIETHOADONSUACHUAs(CHITIETHOADONSUACHUA entity)
		{
			this.SendPropertyChanging();
			entity.BANGSUACHUA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAOCAOTHANG")]
	public partial class BAOCAOTHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaBC;
		
		private System.Nullable<System.DateTime> _NgayLapBC;
		
		private string _NguoiLap;
		
		private System.Nullable<float> _TongDoanhThu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBCChanging(long value);
    partial void OnMaBCChanged();
    partial void OnNgayLapBCChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapBCChanged();
    partial void OnNguoiLapChanging(string value);
    partial void OnNguoiLapChanged();
    partial void OnTongDoanhThuChanging(System.Nullable<float> value);
    partial void OnTongDoanhThuChanged();
    #endregion
		
		public BAOCAOTHANG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBC", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaBC
		{
			get
			{
				return this._MaBC;
			}
			set
			{
				if ((this._MaBC != value))
				{
					this.OnMaBCChanging(value);
					this.SendPropertyChanging();
					this._MaBC = value;
					this.SendPropertyChanged("MaBC");
					this.OnMaBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLapBC", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLapBC
		{
			get
			{
				return this._NgayLapBC;
			}
			set
			{
				if ((this._NgayLapBC != value))
				{
					this.OnNgayLapBCChanging(value);
					this.SendPropertyChanging();
					this._NgayLapBC = value;
					this.SendPropertyChanged("NgayLapBC");
					this.OnNgayLapBCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiLap", DbType="NVarChar(50)")]
		public string NguoiLap
		{
			get
			{
				return this._NguoiLap;
			}
			set
			{
				if ((this._NguoiLap != value))
				{
					this.OnNguoiLapChanging(value);
					this.SendPropertyChanging();
					this._NguoiLap = value;
					this.SendPropertyChanged("NguoiLap");
					this.OnNguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongDoanhThu", DbType="Real")]
		public System.Nullable<float> TongDoanhThu
		{
			get
			{
				return this._TongDoanhThu;
			}
			set
			{
				if ((this._TongDoanhThu != value))
				{
					this.OnTongDoanhThuChanging(value);
					this.SendPropertyChanging();
					this._TongDoanhThu = value;
					this.SendPropertyChanged("TongDoanhThu");
					this.OnTongDoanhThuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHOADONBANHANG")]
	public partial class CHITIETHOADONBANHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaChiTietHD;
		
		private System.Nullable<long> _MaHD;
		
		private System.Nullable<long> _MaMH;
		
		private System.Nullable<long> _SoLuong;
		
		private System.Nullable<double> _DonGia;
		
		private System.Nullable<double> _ThanhTien;
		
		private EntityRef<HOADONBANHANG> _HOADONBANHANG;
		
		private EntityRef<MATHANG> _MATHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChiTietHDChanging(long value);
    partial void OnMaChiTietHDChanged();
    partial void OnMaHDChanging(System.Nullable<long> value);
    partial void OnMaHDChanged();
    partial void OnMaMHChanging(System.Nullable<long> value);
    partial void OnMaMHChanged();
    partial void OnSoLuongChanging(System.Nullable<long> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    partial void OnThanhTienChanging(System.Nullable<double> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public CHITIETHOADONBANHANG()
		{
			this._HOADONBANHANG = default(EntityRef<HOADONBANHANG>);
			this._MATHANG = default(EntityRef<MATHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChiTietHD", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaChiTietHD
		{
			get
			{
				return this._MaChiTietHD;
			}
			set
			{
				if ((this._MaChiTietHD != value))
				{
					this.OnMaChiTietHDChanging(value);
					this.SendPropertyChanging();
					this._MaChiTietHD = value;
					this.SendPropertyChanged("MaChiTietHD");
					this.OnMaChiTietHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="BigInt")]
		public System.Nullable<long> MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._HOADONBANHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", DbType="BigInt")]
		public System.Nullable<long> MaMH
		{
			get
			{
				return this._MaMH;
			}
			set
			{
				if ((this._MaMH != value))
				{
					if (this._MATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMHChanging(value);
					this.SendPropertyChanging();
					this._MaMH = value;
					this.SendPropertyChanged("MaMH");
					this.OnMaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="BigInt")]
		public System.Nullable<long> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
		public System.Nullable<double> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADONBANHANG_CHITIETHOADONBANHANG", Storage="_HOADONBANHANG", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public HOADONBANHANG HOADONBANHANG
		{
			get
			{
				return this._HOADONBANHANG.Entity;
			}
			set
			{
				HOADONBANHANG previousValue = this._HOADONBANHANG.Entity;
				if (((previousValue != value) 
							|| (this._HOADONBANHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADONBANHANG.Entity = null;
						previousValue.CHITIETHOADONBANHANGs.Remove(this);
					}
					this._HOADONBANHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADONBANHANGs.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(Nullable<long>);
					}
					this.SendPropertyChanged("HOADONBANHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATHANG_CHITIETHOADONBANHANG", Storage="_MATHANG", ThisKey="MaMH", OtherKey="MaMH", IsForeignKey=true)]
		public MATHANG MATHANG
		{
			get
			{
				return this._MATHANG.Entity;
			}
			set
			{
				MATHANG previousValue = this._MATHANG.Entity;
				if (((previousValue != value) 
							|| (this._MATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATHANG.Entity = null;
						previousValue.CHITIETHOADONBANHANGs.Remove(this);
					}
					this._MATHANG.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADONBANHANGs.Add(this);
						this._MaMH = value.MaMH;
					}
					else
					{
						this._MaMH = default(Nullable<long>);
					}
					this.SendPropertyChanged("MATHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHOADONSUACHUA")]
	public partial class CHITIETHOADONSUACHUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaCTSC;
		
		private System.Nullable<long> _MaHDSC;
		
		private System.Nullable<long> _MaBSC;
		
		private System.Nullable<long> _SoLuong;
		
		private System.Nullable<double> _DonGia;
		
		private System.Nullable<double> _ThanhTien;
		
		private EntityRef<BANGSUACHUA> _BANGSUACHUA;
		
		private EntityRef<HOADONSUACHUA> _HOADONSUACHUA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTSCChanging(long value);
    partial void OnMaCTSCChanged();
    partial void OnMaHDSCChanging(System.Nullable<long> value);
    partial void OnMaHDSCChanged();
    partial void OnMaBSCChanging(System.Nullable<long> value);
    partial void OnMaBSCChanged();
    partial void OnSoLuongChanging(System.Nullable<long> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    partial void OnThanhTienChanging(System.Nullable<double> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public CHITIETHOADONSUACHUA()
		{
			this._BANGSUACHUA = default(EntityRef<BANGSUACHUA>);
			this._HOADONSUACHUA = default(EntityRef<HOADONSUACHUA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTSC", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaCTSC
		{
			get
			{
				return this._MaCTSC;
			}
			set
			{
				if ((this._MaCTSC != value))
				{
					this.OnMaCTSCChanging(value);
					this.SendPropertyChanging();
					this._MaCTSC = value;
					this.SendPropertyChanged("MaCTSC");
					this.OnMaCTSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDSC", DbType="BigInt")]
		public System.Nullable<long> MaHDSC
		{
			get
			{
				return this._MaHDSC;
			}
			set
			{
				if ((this._MaHDSC != value))
				{
					if (this._HOADONSUACHUA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDSCChanging(value);
					this.SendPropertyChanging();
					this._MaHDSC = value;
					this.SendPropertyChanged("MaHDSC");
					this.OnMaHDSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBSC", DbType="BigInt")]
		public System.Nullable<long> MaBSC
		{
			get
			{
				return this._MaBSC;
			}
			set
			{
				if ((this._MaBSC != value))
				{
					if (this._BANGSUACHUA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBSCChanging(value);
					this.SendPropertyChanging();
					this._MaBSC = value;
					this.SendPropertyChanged("MaBSC");
					this.OnMaBSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="BigInt")]
		public System.Nullable<long> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Float")]
		public System.Nullable<double> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGSUACHUA_CHITIETHOADONSUACHUA", Storage="_BANGSUACHUA", ThisKey="MaBSC", OtherKey="MaBSC", IsForeignKey=true)]
		public BANGSUACHUA BANGSUACHUA
		{
			get
			{
				return this._BANGSUACHUA.Entity;
			}
			set
			{
				BANGSUACHUA previousValue = this._BANGSUACHUA.Entity;
				if (((previousValue != value) 
							|| (this._BANGSUACHUA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANGSUACHUA.Entity = null;
						previousValue.CHITIETHOADONSUACHUAs.Remove(this);
					}
					this._BANGSUACHUA.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADONSUACHUAs.Add(this);
						this._MaBSC = value.MaBSC;
					}
					else
					{
						this._MaBSC = default(Nullable<long>);
					}
					this.SendPropertyChanged("BANGSUACHUA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADONSUACHUA_CHITIETHOADONSUACHUA", Storage="_HOADONSUACHUA", ThisKey="MaHDSC", OtherKey="MaHDSC", IsForeignKey=true)]
		public HOADONSUACHUA HOADONSUACHUA
		{
			get
			{
				return this._HOADONSUACHUA.Entity;
			}
			set
			{
				HOADONSUACHUA previousValue = this._HOADONSUACHUA.Entity;
				if (((previousValue != value) 
							|| (this._HOADONSUACHUA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADONSUACHUA.Entity = null;
						previousValue.CHITIETHOADONSUACHUAs.Remove(this);
					}
					this._HOADONSUACHUA.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADONSUACHUAs.Add(this);
						this._MaHDSC = value.MaHDSC;
					}
					else
					{
						this._MaHDSC = default(Nullable<long>);
					}
					this.SendPropertyChanged("HOADONSUACHUA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITTIETHOADONDICHVU")]
	public partial class CHITTIETHOADONDICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaCTDV;
		
		private System.Nullable<long> _MaHDDV;
		
		private System.Nullable<long> _MaDV;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<double> _DonGia;
		
		private EntityRef<DICHVU> _DICHVU;
		
		private EntityRef<HOADONDICHVU> _HOADONDICHVU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTDVChanging(long value);
    partial void OnMaCTDVChanged();
    partial void OnMaHDDVChanging(System.Nullable<long> value);
    partial void OnMaHDDVChanged();
    partial void OnMaDVChanging(System.Nullable<long> value);
    partial void OnMaDVChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public CHITTIETHOADONDICHVU()
		{
			this._DICHVU = default(EntityRef<DICHVU>);
			this._HOADONDICHVU = default(EntityRef<HOADONDICHVU>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTDV", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaCTDV
		{
			get
			{
				return this._MaCTDV;
			}
			set
			{
				if ((this._MaCTDV != value))
				{
					this.OnMaCTDVChanging(value);
					this.SendPropertyChanging();
					this._MaCTDV = value;
					this.SendPropertyChanged("MaCTDV");
					this.OnMaCTDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDDV", DbType="BigInt")]
		public System.Nullable<long> MaHDDV
		{
			get
			{
				return this._MaHDDV;
			}
			set
			{
				if ((this._MaHDDV != value))
				{
					if (this._HOADONDICHVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDDVChanging(value);
					this.SendPropertyChanging();
					this._MaHDDV = value;
					this.SendPropertyChanged("MaHDDV");
					this.OnMaHDDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", DbType="BigInt")]
		public System.Nullable<long> MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					if (this._DICHVU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_CHITTIETHOADONDICHVU", Storage="_DICHVU", ThisKey="MaDV", OtherKey="MaDV", IsForeignKey=true)]
		public DICHVU DICHVU
		{
			get
			{
				return this._DICHVU.Entity;
			}
			set
			{
				DICHVU previousValue = this._DICHVU.Entity;
				if (((previousValue != value) 
							|| (this._DICHVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DICHVU.Entity = null;
						previousValue.CHITTIETHOADONDICHVUs.Remove(this);
					}
					this._DICHVU.Entity = value;
					if ((value != null))
					{
						value.CHITTIETHOADONDICHVUs.Add(this);
						this._MaDV = value.MaDV;
					}
					else
					{
						this._MaDV = default(Nullable<long>);
					}
					this.SendPropertyChanged("DICHVU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADONDICHVU_CHITTIETHOADONDICHVU", Storage="_HOADONDICHVU", ThisKey="MaHDDV", OtherKey="MaHDDV", IsForeignKey=true)]
		public HOADONDICHVU HOADONDICHVU
		{
			get
			{
				return this._HOADONDICHVU.Entity;
			}
			set
			{
				HOADONDICHVU previousValue = this._HOADONDICHVU.Entity;
				if (((previousValue != value) 
							|| (this._HOADONDICHVU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADONDICHVU.Entity = null;
						previousValue.CHITTIETHOADONDICHVUs.Remove(this);
					}
					this._HOADONDICHVU.Entity = value;
					if ((value != null))
					{
						value.CHITTIETHOADONDICHVUs.Add(this);
						this._MaHDDV = value.MaHDDV;
					}
					else
					{
						this._MaHDDV = default(Nullable<long>);
					}
					this.SendPropertyChanged("HOADONDICHVU");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DICHVU")]
	public partial class DICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaDV;
		
		private string _TenDV;
		
		private System.Nullable<double> _DonGia;
		
		private EntitySet<CHITTIETHOADONDICHVU> _CHITTIETHOADONDICHVUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDVChanging(long value);
    partial void OnMaDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnDonGiaChanging(System.Nullable<double> value);
    partial void OnDonGiaChanged();
    #endregion
		
		public DICHVU()
		{
			this._CHITTIETHOADONDICHVUs = new EntitySet<CHITTIETHOADONDICHVU>(new Action<CHITTIETHOADONDICHVU>(this.attach_CHITTIETHOADONDICHVUs), new Action<CHITTIETHOADONDICHVU>(this.detach_CHITTIETHOADONDICHVUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDV", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaDV
		{
			get
			{
				return this._MaDV;
			}
			set
			{
				if ((this._MaDV != value))
				{
					this.OnMaDVChanging(value);
					this.SendPropertyChanging();
					this._MaDV = value;
					this.SendPropertyChanged("MaDV");
					this.OnMaDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(50)")]
		public string TenDV
		{
			get
			{
				return this._TenDV;
			}
			set
			{
				if ((this._TenDV != value))
				{
					this.OnTenDVChanging(value);
					this.SendPropertyChanging();
					this._TenDV = value;
					this.SendPropertyChanged("TenDV");
					this.OnTenDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Float")]
		public System.Nullable<double> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DICHVU_CHITTIETHOADONDICHVU", Storage="_CHITTIETHOADONDICHVUs", ThisKey="MaDV", OtherKey="MaDV")]
		public EntitySet<CHITTIETHOADONDICHVU> CHITTIETHOADONDICHVUs
		{
			get
			{
				return this._CHITTIETHOADONDICHVUs;
			}
			set
			{
				this._CHITTIETHOADONDICHVUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITTIETHOADONDICHVUs(CHITTIETHOADONDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = this;
		}
		
		private void detach_CHITTIETHOADONDICHVUs(CHITTIETHOADONDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.DICHVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANGSANXUAT")]
	public partial class HANGSANXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenHangSX;
		
		private string _MoTa;
		
		private EntitySet<MATHANG> _MATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenHangSXChanging(string value);
    partial void OnTenHangSXChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public HANGSANXUAT()
		{
			this._MATHANGs = new EntitySet<MATHANG>(new Action<MATHANG>(this.attach_MATHANGs), new Action<MATHANG>(this.detach_MATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHangSX", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenHangSX
		{
			get
			{
				return this._TenHangSX;
			}
			set
			{
				if ((this._TenHangSX != value))
				{
					this.OnTenHangSXChanging(value);
					this.SendPropertyChanging();
					this._TenHangSX = value;
					this.SendPropertyChanged("TenHangSX");
					this.OnTenHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANGSANXUAT_MATHANG", Storage="_MATHANGs", ThisKey="TenHangSX", OtherKey="TenHangSX")]
		public EntitySet<MATHANG> MATHANGs
		{
			get
			{
				return this._MATHANGs;
			}
			set
			{
				this._MATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MATHANGs(MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.HANGSANXUAT = this;
		}
		
		private void detach_MATHANGs(MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.HANGSANXUAT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADONBANHANG")]
	public partial class HOADONBANHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaHD;
		
		private string _TenKH;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<float> _TongTien;
		
		private EntitySet<CHITIETHOADONBANHANG> _CHITIETHOADONBANHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(long value);
    partial void OnMaHDChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnTongTienChanging(System.Nullable<float> value);
    partial void OnTongTienChanged();
    #endregion
		
		public HOADONBANHANG()
		{
			this._CHITIETHOADONBANHANGs = new EntitySet<CHITIETHOADONBANHANG>(new Action<CHITIETHOADONBANHANG>(this.attach_CHITIETHOADONBANHANGs), new Action<CHITIETHOADONBANHANG>(this.detach_CHITIETHOADONBANHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Real")]
		public System.Nullable<float> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADONBANHANG_CHITIETHOADONBANHANG", Storage="_CHITIETHOADONBANHANGs", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<CHITIETHOADONBANHANG> CHITIETHOADONBANHANGs
		{
			get
			{
				return this._CHITIETHOADONBANHANGs;
			}
			set
			{
				this._CHITIETHOADONBANHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOADONBANHANGs(CHITIETHOADONBANHANG entity)
		{
			this.SendPropertyChanging();
			entity.HOADONBANHANG = this;
		}
		
		private void detach_CHITIETHOADONBANHANGs(CHITIETHOADONBANHANG entity)
		{
			this.SendPropertyChanging();
			entity.HOADONBANHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADONDICHVU")]
	public partial class HOADONDICHVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaHDDV;
		
		private string _TenKH;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private System.Nullable<float> _TongTien;
		
		private EntitySet<CHITTIETHOADONDICHVU> _CHITTIETHOADONDICHVUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDDVChanging(long value);
    partial void OnMaHDDVChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnTongTienChanging(System.Nullable<float> value);
    partial void OnTongTienChanged();
    #endregion
		
		public HOADONDICHVU()
		{
			this._CHITTIETHOADONDICHVUs = new EntitySet<CHITTIETHOADONDICHVU>(new Action<CHITTIETHOADONDICHVU>(this.attach_CHITTIETHOADONDICHVUs), new Action<CHITTIETHOADONDICHVU>(this.detach_CHITTIETHOADONDICHVUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDDV", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaHDDV
		{
			get
			{
				return this._MaHDDV;
			}
			set
			{
				if ((this._MaHDDV != value))
				{
					this.OnMaHDDVChanging(value);
					this.SendPropertyChanging();
					this._MaHDDV = value;
					this.SendPropertyChanged("MaHDDV");
					this.OnMaHDDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Real")]
		public System.Nullable<float> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADONDICHVU_CHITTIETHOADONDICHVU", Storage="_CHITTIETHOADONDICHVUs", ThisKey="MaHDDV", OtherKey="MaHDDV")]
		public EntitySet<CHITTIETHOADONDICHVU> CHITTIETHOADONDICHVUs
		{
			get
			{
				return this._CHITTIETHOADONDICHVUs;
			}
			set
			{
				this._CHITTIETHOADONDICHVUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITTIETHOADONDICHVUs(CHITTIETHOADONDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.HOADONDICHVU = this;
		}
		
		private void detach_CHITTIETHOADONDICHVUs(CHITTIETHOADONDICHVU entity)
		{
			this.SendPropertyChanging();
			entity.HOADONDICHVU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADONSUACHUA")]
	public partial class HOADONSUACHUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaHDSC;
		
		private System.Nullable<long> _MaPH;
		
		private string _TenKH;
		
		private System.Nullable<System.DateTime> _NgayTra;
		
		private System.Nullable<float> _TongTien;
		
		private EntitySet<CHITIETHOADONSUACHUA> _CHITIETHOADONSUACHUAs;
		
		private EntityRef<PHIEUHEN> _PHIEUHEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDSCChanging(long value);
    partial void OnMaHDSCChanged();
    partial void OnMaPHChanging(System.Nullable<long> value);
    partial void OnMaPHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnNgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraChanged();
    partial void OnTongTienChanging(System.Nullable<float> value);
    partial void OnTongTienChanged();
    #endregion
		
		public HOADONSUACHUA()
		{
			this._CHITIETHOADONSUACHUAs = new EntitySet<CHITIETHOADONSUACHUA>(new Action<CHITIETHOADONSUACHUA>(this.attach_CHITIETHOADONSUACHUAs), new Action<CHITIETHOADONSUACHUA>(this.detach_CHITIETHOADONSUACHUAs));
			this._PHIEUHEN = default(EntityRef<PHIEUHEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHDSC", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaHDSC
		{
			get
			{
				return this._MaHDSC;
			}
			set
			{
				if ((this._MaHDSC != value))
				{
					this.OnMaHDSCChanging(value);
					this.SendPropertyChanging();
					this._MaHDSC = value;
					this.SendPropertyChanged("MaHDSC");
					this.OnMaHDSCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPH", DbType="BigInt")]
		public System.Nullable<long> MaPH
		{
			get
			{
				return this._MaPH;
			}
			set
			{
				if ((this._MaPH != value))
				{
					if (this._PHIEUHEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPHChanging(value);
					this.SendPropertyChanging();
					this._MaPH = value;
					this.SendPropertyChanged("MaPH");
					this.OnMaPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Real")]
		public System.Nullable<float> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADONSUACHUA_CHITIETHOADONSUACHUA", Storage="_CHITIETHOADONSUACHUAs", ThisKey="MaHDSC", OtherKey="MaHDSC")]
		public EntitySet<CHITIETHOADONSUACHUA> CHITIETHOADONSUACHUAs
		{
			get
			{
				return this._CHITIETHOADONSUACHUAs;
			}
			set
			{
				this._CHITIETHOADONSUACHUAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUHEN_HOADONSUACHUA", Storage="_PHIEUHEN", ThisKey="MaPH", OtherKey="MaPH", IsForeignKey=true)]
		public PHIEUHEN PHIEUHEN
		{
			get
			{
				return this._PHIEUHEN.Entity;
			}
			set
			{
				PHIEUHEN previousValue = this._PHIEUHEN.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUHEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUHEN.Entity = null;
						previousValue.HOADONSUACHUAs.Remove(this);
					}
					this._PHIEUHEN.Entity = value;
					if ((value != null))
					{
						value.HOADONSUACHUAs.Add(this);
						this._MaPH = value.MaPH;
					}
					else
					{
						this._MaPH = default(Nullable<long>);
					}
					this.SendPropertyChanged("PHIEUHEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOADONSUACHUAs(CHITIETHOADONSUACHUA entity)
		{
			this.SendPropertyChanging();
			entity.HOADONSUACHUA = this;
		}
		
		private void detach_CHITIETHOADONSUACHUAs(CHITIETHOADONSUACHUA entity)
		{
			this.SendPropertyChanging();
			entity.HOADONSUACHUA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIMATHANG")]
	public partial class LOAIMATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenLoaiMH;
		
		private string _MoTa;
		
		private EntitySet<MATHANG> _MATHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenLoaiMHChanging(string value);
    partial void OnTenLoaiMHChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public LOAIMATHANG()
		{
			this._MATHANGs = new EntitySet<MATHANG>(new Action<MATHANG>(this.attach_MATHANGs), new Action<MATHANG>(this.detach_MATHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiMH", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenLoaiMH
		{
			get
			{
				return this._TenLoaiMH;
			}
			set
			{
				if ((this._TenLoaiMH != value))
				{
					this.OnTenLoaiMHChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiMH = value;
					this.SendPropertyChanged("TenLoaiMH");
					this.OnTenLoaiMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIMATHANG_MATHANG", Storage="_MATHANGs", ThisKey="TenLoaiMH", OtherKey="TenLoaiMH")]
		public EntitySet<MATHANG> MATHANGs
		{
			get
			{
				return this._MATHANGs;
			}
			set
			{
				this._MATHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MATHANGs(MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIMATHANG = this;
		}
		
		private void detach_MATHANGs(MATHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIMATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATHANG")]
	public partial class MATHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaMH;
		
		private string _TenLoaiMH;
		
		private string _TenMH;
		
		private System.Nullable<float> _DonGia;
		
		private string _TenHangSX;
		
		private string _NamSX;
		
		private System.Nullable<int> _SoLuong;
		
		private string _Mota;
		
		private System.Nullable<bool> _KinhDoanh;
		
		private EntitySet<CHITIETHOADONBANHANG> _CHITIETHOADONBANHANGs;
		
		private EntityRef<HANGSANXUAT> _HANGSANXUAT;
		
		private EntityRef<LOAIMATHANG> _LOAIMATHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMHChanging(long value);
    partial void OnMaMHChanged();
    partial void OnTenLoaiMHChanging(string value);
    partial void OnTenLoaiMHChanged();
    partial void OnTenMHChanging(string value);
    partial void OnTenMHChanged();
    partial void OnDonGiaChanging(System.Nullable<float> value);
    partial void OnDonGiaChanged();
    partial void OnTenHangSXChanging(string value);
    partial void OnTenHangSXChanged();
    partial void OnNamSXChanging(string value);
    partial void OnNamSXChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnKinhDoanhChanging(System.Nullable<bool> value);
    partial void OnKinhDoanhChanged();
    #endregion
		
		public MATHANG()
		{
			this._CHITIETHOADONBANHANGs = new EntitySet<CHITIETHOADONBANHANG>(new Action<CHITIETHOADONBANHANG>(this.attach_CHITIETHOADONBANHANGs), new Action<CHITIETHOADONBANHANG>(this.detach_CHITIETHOADONBANHANGs));
			this._HANGSANXUAT = default(EntityRef<HANGSANXUAT>);
			this._LOAIMATHANG = default(EntityRef<LOAIMATHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMH", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaMH
		{
			get
			{
				return this._MaMH;
			}
			set
			{
				if ((this._MaMH != value))
				{
					this.OnMaMHChanging(value);
					this.SendPropertyChanging();
					this._MaMH = value;
					this.SendPropertyChanged("MaMH");
					this.OnMaMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiMH", DbType="NVarChar(50)")]
		public string TenLoaiMH
		{
			get
			{
				return this._TenLoaiMH;
			}
			set
			{
				if ((this._TenLoaiMH != value))
				{
					if (this._LOAIMATHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenLoaiMHChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiMH = value;
					this.SendPropertyChanged("TenLoaiMH");
					this.OnTenLoaiMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMH", DbType="NVarChar(100)")]
		public string TenMH
		{
			get
			{
				return this._TenMH;
			}
			set
			{
				if ((this._TenMH != value))
				{
					this.OnTenMHChanging(value);
					this.SendPropertyChanging();
					this._TenMH = value;
					this.SendPropertyChanged("TenMH");
					this.OnTenMHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="Real")]
		public System.Nullable<float> DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHangSX", DbType="NVarChar(50)")]
		public string TenHangSX
		{
			get
			{
				return this._TenHangSX;
			}
			set
			{
				if ((this._TenHangSX != value))
				{
					if (this._HANGSANXUAT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenHangSXChanging(value);
					this.SendPropertyChanging();
					this._TenHangSX = value;
					this.SendPropertyChanged("TenHangSX");
					this.OnTenHangSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSX", DbType="NVarChar(10)")]
		public string NamSX
		{
			get
			{
				return this._NamSX;
			}
			set
			{
				if ((this._NamSX != value))
				{
					this.OnNamSXChanging(value);
					this.SendPropertyChanging();
					this._NamSX = value;
					this.SendPropertyChanged("NamSX");
					this.OnNamSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(100)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhDoanh", DbType="Bit")]
		public System.Nullable<bool> KinhDoanh
		{
			get
			{
				return this._KinhDoanh;
			}
			set
			{
				if ((this._KinhDoanh != value))
				{
					this.OnKinhDoanhChanging(value);
					this.SendPropertyChanging();
					this._KinhDoanh = value;
					this.SendPropertyChanged("KinhDoanh");
					this.OnKinhDoanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATHANG_CHITIETHOADONBANHANG", Storage="_CHITIETHOADONBANHANGs", ThisKey="MaMH", OtherKey="MaMH")]
		public EntitySet<CHITIETHOADONBANHANG> CHITIETHOADONBANHANGs
		{
			get
			{
				return this._CHITIETHOADONBANHANGs;
			}
			set
			{
				this._CHITIETHOADONBANHANGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANGSANXUAT_MATHANG", Storage="_HANGSANXUAT", ThisKey="TenHangSX", OtherKey="TenHangSX", IsForeignKey=true)]
		public HANGSANXUAT HANGSANXUAT
		{
			get
			{
				return this._HANGSANXUAT.Entity;
			}
			set
			{
				HANGSANXUAT previousValue = this._HANGSANXUAT.Entity;
				if (((previousValue != value) 
							|| (this._HANGSANXUAT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HANGSANXUAT.Entity = null;
						previousValue.MATHANGs.Remove(this);
					}
					this._HANGSANXUAT.Entity = value;
					if ((value != null))
					{
						value.MATHANGs.Add(this);
						this._TenHangSX = value.TenHangSX;
					}
					else
					{
						this._TenHangSX = default(string);
					}
					this.SendPropertyChanged("HANGSANXUAT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIMATHANG_MATHANG", Storage="_LOAIMATHANG", ThisKey="TenLoaiMH", OtherKey="TenLoaiMH", IsForeignKey=true)]
		public LOAIMATHANG LOAIMATHANG
		{
			get
			{
				return this._LOAIMATHANG.Entity;
			}
			set
			{
				LOAIMATHANG previousValue = this._LOAIMATHANG.Entity;
				if (((previousValue != value) 
							|| (this._LOAIMATHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIMATHANG.Entity = null;
						previousValue.MATHANGs.Remove(this);
					}
					this._LOAIMATHANG.Entity = value;
					if ((value != null))
					{
						value.MATHANGs.Add(this);
						this._TenLoaiMH = value.TenLoaiMH;
					}
					else
					{
						this._TenLoaiMH = default(string);
					}
					this.SendPropertyChanged("LOAIMATHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOADONBANHANGs(CHITIETHOADONBANHANG entity)
		{
			this.SendPropertyChanging();
			entity.MATHANG = this;
		}
		
		private void detach_CHITIETHOADONBANHANGs(CHITIETHOADONBANHANG entity)
		{
			this.SendPropertyChanging();
			entity.MATHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUHEN")]
	public partial class PHIEUHEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaPH;
		
		private System.Nullable<System.DateTime> _NgayLap;
		
		private string _TenKH;
		
		private string _SoDT;
		
		private string _TinhTrangMay;
		
		private EntitySet<HOADONSUACHUA> _HOADONSUACHUAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPHChanging(long value);
    partial void OnMaPHChanged();
    partial void OnNgayLapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayLapChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnTinhTrangMayChanging(string value);
    partial void OnTinhTrangMayChanged();
    #endregion
		
		public PHIEUHEN()
		{
			this._HOADONSUACHUAs = new EntitySet<HOADONSUACHUA>(new Action<HOADONSUACHUA>(this.attach_HOADONSUACHUAs), new Action<HOADONSUACHUA>(this.detach_HOADONSUACHUAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPH", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaPH
		{
			get
			{
				return this._MaPH;
			}
			set
			{
				if ((this._MaPH != value))
				{
					this.OnMaPHChanging(value);
					this.SendPropertyChanging();
					this._MaPH = value;
					this.SendPropertyChanged("MaPH");
					this.OnMaPHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="Date")]
		public System.Nullable<System.DateTime> NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(50)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="NVarChar(15)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrangMay", DbType="NVarChar(MAX)")]
		public string TinhTrangMay
		{
			get
			{
				return this._TinhTrangMay;
			}
			set
			{
				if ((this._TinhTrangMay != value))
				{
					this.OnTinhTrangMayChanging(value);
					this.SendPropertyChanging();
					this._TinhTrangMay = value;
					this.SendPropertyChanged("TinhTrangMay");
					this.OnTinhTrangMayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUHEN_HOADONSUACHUA", Storage="_HOADONSUACHUAs", ThisKey="MaPH", OtherKey="MaPH")]
		public EntitySet<HOADONSUACHUA> HOADONSUACHUAs
		{
			get
			{
				return this._HOADONSUACHUAs;
			}
			set
			{
				this._HOADONSUACHUAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONSUACHUAs(HOADONSUACHUA entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUHEN = this;
		}
		
		private void detach_HOADONSUACHUAs(HOADONSUACHUA entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUHEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUYDINH")]
	public partial class QUYDINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MaQD;
		
		private string _TenQD;
		
		private string _Mota;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaQDChanging(long value);
    partial void OnMaQDChanged();
    partial void OnTenQDChanging(string value);
    partial void OnTenQDChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    #endregion
		
		public QUYDINH()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQD", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MaQD
		{
			get
			{
				return this._MaQD;
			}
			set
			{
				if ((this._MaQD != value))
				{
					this.OnMaQDChanging(value);
					this.SendPropertyChanging();
					this._MaQD = value;
					this.SendPropertyChanged("MaQD");
					this.OnMaQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQD", DbType="NVarChar(25)")]
		public string TenQD
		{
			get
			{
				return this._TenQD;
			}
			set
			{
				if ((this._TenQD != value))
				{
					this.OnTenQDChanging(value);
					this.SendPropertyChanging();
					this._TenQD = value;
					this.SendPropertyChanged("TenQD");
					this.OnTenQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(100)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
