using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using QLCuaHangDDS.BUS;
using QLCuaHangDDS.DAO;

namespace QLCuaHangDDS.GUI.ManHinhBangSuaChua
{
    
    public partial class BangSuaChua : DevExpress.XtraEditors.XtraForm
    {
        private string selectedTenMHSC;

        public BangSuaChua()
        {

            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            BangSuaChua_table.DataSource = new QLCuaHangDDS.DAO.QLCuaHangDDSDBDataContext().BANGSUACHUAs;
            BangSuaChua_gv.Columns[0].Caption = "Tên thông tin sửa chữa";
            BangSuaChua_gv.Columns[1].Caption = "Chi phí sửa chữa";
        }

        private void BangSuaChua_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'qLCuaHangDDSDataSet.BANGSUACHUA' table. You can move, or remove it, as needed.
        

        }
        private void refreshData()
        {
            // This line of code is generated by Data Source Configuration Wizard
            BangSuaChua_table.DataSource = new QLCuaHangDDS.DAO.QLCuaHangDDSDBDataContext().BANGSUACHUAs;
            BangSuaChua_gv.Columns[0].Caption = "Tên thông tin sửa chữa";
            BangSuaChua_gv.Columns[1].Caption = "Chi phí sửa chữa";
        }
        

        private void btn_Them_Click(object sender, EventArgs e)
        {

            if (!BangSuaChuaBUS.isValidFloat(edt_ChiPhiSC.Text.ToString()))
            {
                XtraMessageBox.Show("Thông tin không hợp lệ!Vui lòng kiểm tra lại", "Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            DAO.BANGSUACHUA bsc = new DAO.BANGSUACHUA();
            bsc.TenMHSC = edt_TenSC.Text.ToString();
            bsc.ChiPhiSuaChua = System.Convert.ToDecimal(edt_ChiPhiSC.Text.ToString());
            if (BangSuaChuaBUS.ThemBangSuaChua(bsc))
            {
                XtraMessageBox.Show("Thêm thành công!", "Succeed!", MessageBoxButtons.OK, MessageBoxIcon.Information);
                refreshData();
                return;
            }
            else
            {
                XtraMessageBox.Show("Thêm thất bại! Vui lòng xem lại thông tin", "Failed!", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
        }
        private void gridView_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
          
            try
            {
                this.selectedTenMHSC = BangSuaChua_gv.GetRowCellValue(BangSuaChua_gv.FocusedRowHandle, "TenMHSC").ToString();
            }
            catch (Exception) { }
           
        }

        private void btn_Sua_Click(object sender, EventArgs e)
        {

            if (!MatHangBUS.isValidFloat(BangSuaChua_gv.GetRowCellValue(BangSuaChua_gv.FocusedRowHandle, "ChiPhiSuaChua")))
            {
                XtraMessageBox.Show("Chi phí không hợp lệ!", "Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
            BANGSUACHUA bsc = new BANGSUACHUA();
            bsc.TenMHSC = BangSuaChua_gv.GetRowCellValue(BangSuaChua_gv.FocusedRowHandle, "TenMHSC").ToString();
            bsc.ChiPhiSuaChua= System.Convert.ToDecimal(BangSuaChua_gv.GetRowCellValue(BangSuaChua_gv.FocusedRowHandle, "ChiPhiSuaChua").ToString());
             if (BangSuaChuaBUS.SuaBangSuaChua(this.selectedTenMHSC, bsc))
            {
                XtraMessageBox.Show("Cập nhật thành công!", "Succeed", MessageBoxButtons.OK, MessageBoxIcon.Information);
                this.refreshData();
                return;
            }
            else
            {
                XtraMessageBox.Show("Cập nhật thất bại!", "Failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

        }

        private void BangSuaChua_gv_FocusedRowChanged(object sender, DevExpress.XtraGrid.Views.Base.FocusedRowChangedEventArgs e)
        {
            btn_Sua.Enabled = true;
            try
            {
                this.selectedTenMHSC = BangSuaChua_gv.GetFocusedRowCellValue("TenMHSC").ToString();
            }
            catch (Exception) { }
        }
    }
}